package com.chattriggers.ctjs.launch.plugin

const val CRASH_REPORT_CATEGORY = "net/minecraft/crash/CrashReportCategory"
const val CLIENT_LISTENER = "com/chattriggers/ctjs/minecraft/listeners/ClientListener"
const val ENTITY_PLAYER = "net/minecraft/entity/player/EntityPlayer"
const val ENTITY_ITEM = "net/minecraft/entity/item/EntityItem"
const val ITEM_STACK = "net/minecraft/item/ItemStack"
const val INVENTORY_PLAYER = "net/minecraft/entity/player/InventoryPlayer"
const val FILE = "java/io/File"
const val FRAME_BUFFER = "net/minecraft/client/shader/Framebuffer"
const val ICHAT_COMPONENT = "net/minecraft/util/IChatComponent"
const val EFFECT_RENDERER = "net/minecraft/client/particle/EffectRenderer"
const val TRIGGER_TYPE = "com/chattriggers/ctjs/triggers/TriggerType"
const val ENTITY_FX = "net/minecraft/client/particle/EntityFX"
const val ENTITY = "net/minecraft/entity/Entity"
const val PACKET = "net/minecraft/network/Packet"
const val CANCELLABLE_EVENT = "com/chattriggers/ctjs/minecraft/listeners/CancellableEvent"
