name: build

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew --no-daemon setupCiWorkspace build

      - name: Get Short SHA
        id: sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ChatTriggers-artifacts-${{ steps.sha.outputs.sha_short }}
          path: |
            build/libs/*
