name: javadocs

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Deploy Javadocs
    runs-on: "ubuntu-latest"
    if:
      ${{ github.repository == 'ChatTriggers/ChatTriggers' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Javadocs
        run: ./gradlew --no-daemon setupCiWorkspace userdocs

      - name: Publish Javadocs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: build/javadoc/
          target: /srv/www/static/home/javadocs
          strip_components: 2
          rm: true

      - name: Set File Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: chmod -R g+w /srv/www/static/home/javadocs
